// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBp07wC0XRpQQC8C55UMBOq2sob7vjDg8',
    appId: '1:166599843065:web:e7c429748a149d70a21628',
    messagingSenderId: '166599843065',
    projectId: 'pokeproyect-51544',
    authDomain: 'pokeproyect-51544.firebaseapp.com',
    storageBucket: 'pokeproyect-51544.appspot.com',
    measurementId: 'G-WNZCV7XN3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE8aXKy2yASDtBFIEf06-eZQW7UYlClrE',
    appId: '1:166599843065:android:44b93f428468867ba21628',
    messagingSenderId: '166599843065',
    projectId: 'pokeproyect-51544',
    storageBucket: 'pokeproyect-51544.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_silaXEwMZP4aCsIk9K-lcKOV4JqZikQ',
    appId: '1:166599843065:ios:9f8478793ede2403a21628',
    messagingSenderId: '166599843065',
    projectId: 'pokeproyect-51544',
    storageBucket: 'pokeproyect-51544.appspot.com',
    iosClientId: '166599843065-m229vokm444p86pp3tk9am9me730cohc.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_silaXEwMZP4aCsIk9K-lcKOV4JqZikQ',
    appId: '1:166599843065:ios:c3f27c4702ec1b01a21628',
    messagingSenderId: '166599843065',
    projectId: 'pokeproyect-51544',
    storageBucket: 'pokeproyect-51544.appspot.com',
    iosClientId: '166599843065-pof0itv6dg9op1o53577avn97umbctl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexMobile.RunnerTests',
  );
}
